// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtVDiimUTwGDGfaczKJd--hW9FsduIio',
    appId: '1:568976584752:web:b620d415933693ebcc3df5',
    messagingSenderId: '568976584752',
    projectId: 'campusconnect-3e670',
    authDomain: 'campusconnect-3e670.firebaseapp.com',
    storageBucket: 'campusconnect-3e670.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-pTuZBgl5ZL0_gqYinG1t32QSDRjXn4',
    appId: '1:568976584752:android:eaadcd9797f3345dcc3df5',
    messagingSenderId: '568976584752',
    projectId: 'campusconnect-3e670',
    storageBucket: 'campusconnect-3e670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZfCs_LAde2oMNKqxFcAfvpEcccUpUCig',
    appId: '1:568976584752:ios:1c6caa5cf5ccdf4bcc3df5',
    messagingSenderId: '568976584752',
    projectId: 'campusconnect-3e670',
    storageBucket: 'campusconnect-3e670.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );
}
